### ISSUE TITLE
deadline update test failure: AttributeError: 'NoneType' object has no attribute 'send'

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/ClassMateBot#122]
For branch: https://github.com/CSC510-Group-25/ClassMateBot/tree/group25-deadline-enhance

https://github.com/CSC510-Group-25/ClassMateBot/runs/4342937670?check_suite_focus=true

**Comment by snapcat** [comment]
https://github.com/CSC510-Group-25/ClassMateBot/blob/542f31e5b9c675015de668a84047efc27a14356d/cogs/deadline.py#L544-L558

https://github.com/CSC510-Group-25/ClassMateBot/blob/542f31e5b9c675015de668a84047efc27a14356d/cogs/deadline.py#L576-L591

**Comment by etracey7** [comment]
Need to integrate with Jonathan's branch so a channel for reminders/assignments exists. Also planning to wrap in if statement to make sure channel is valid

**Comment by snapcat** [comment]
Added suggestion in PR review! #125

**Comment by snapcat** [comment]
Resolved in #125
