### ISSUE TITLE
Enhance Reminders/Deadlines

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/ClassMateBot#18]
- [x] #19
- [x] #20
- [x] #21
- [x] #22

https://github.com/SE21-Team2/ClassMateBot/issues/33

**Comment by etracey7** [comment]
Planning on working on some of these tasks. lmk of any conflicts

**Comment by snapcat** [comment]
@etracey7 is currently working on:

Send real-time reminders #20
Command that gives users the format for reminder commands so they can just copy and edit. #21
Reminders: use user system time OR convert to UTC #22
