### ISSUE TITLE
Make reminders a private command where only the current user can see their own reminders

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/ClassMateBot#19]
DMs are suggested

**Comment by snapcat** [comment]
This is a pointless command. Students don't need personal reminders.

It would be simple enough to have the bot DM reminders instead when the following commands are used:

$coursedue: display all the homeworks that are due for a specific course
$duethisweek: display all the homeworks that are due this week for all the courses (should be changed for the channel the command is called from.)
$duetoday: display all the homeworks that are due today for all the courses (should be changed for the channel the command is called from.)
$listreminders: display all the homeworks that are due for all the courses (should be changed for the channel the command is called from.)

**Comment by etracey7** [comment]
@snapcat I agree that this might be pointless, but I'll confirm that reminders can be sent to PM when used

**Comment by snapcat** [comment]
#125

Users can now use the $duetoday command to have the bot DM any upcoming assignments.
