### ISSUE TITLE
Reminders: use user system time OR convert to UTC

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/ClassMateBot#22]
Use the user's system time to create reminders OR 
Create a converter to convert the user's time to UTC so that it can be used for reminders

**Comment by snapcat** [comment]
Could take advantage of $timenow in deadline.py, maybe?

**Comment by etracey7** [comment]
Considering changing logic to use time deltas instead of dates when reminder is sent and adding option to set timezone when creating reminders. 

Example - HW 1 is due in 1 day and 3 hours

**Comment by etracey7** [comment]
Made time assignments much more flexible and can optionally include timezone.
Duetoday and duethisweek give time delta.
Other listings of time now have timezone attached.
