### ISSUE TITLE
Add markdown docs for each new command (keep this issue up to date!)

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/ClassMateBot#91]
TODO:

polling.py:
- [x] poll
- [x] quizpoll

See #88 
qanda.py
- [x] getAnswersFor
- [x] DALLAF
- [x] archiveQA
- [x] deleteAllQA
- [x] deleteQuestion
- [x] channelGhost
- [x] allChannelGhosts
- [x] reviveGhost
- [x] unearthZombies
- [x] spooky

bot.py
- [x] toggleFilter
- [x] whitelist
- [x] dewhitelist

**Comment by etracey7** [comment]
Added 

- [ ] overdue
- [ ] clearoverdue
